# Cresate db
CREATE DATABASE freshnewsletter;

# Create mysql user
GRANT ALL PRIVILEGES ON freshnewsletter.* TO 'freshnewsletter'@'localhost' IDENTIFIED BY 'toor';
GRANT ALL PRIVILEGES ON freshnewsletter.* TO 'freshnewsletter'@127.0.0.1 IDENTIFIED BY 'toor';
FLUSH PRIVILEGES;


# Mysql user
# GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, INDEX, ALTER
# GRANT EXECUTE, PROCESS, SELECT, SHOW DATABASES, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP,
# EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, CREATE USER, FILE, LOCK TABLES, RELOAD, REPLICATION CLIENT, REPLICATION SLAVE, SHUTDOWN, SUPER

# Mysql user
# GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY 'toor';
# GRANT ALL PRIVILEGES ON *.* TO 'root'@127.0.0.1 IDENTIFIED BY 'toor';
# FLUSH PRIVILEGES;
 
# All options
# GRANT ALL PRIVILEGES ON *.* TO 'root'@127.0.0.1 IDENTIFIED BY 'toor' WITH GRANT OPTION;
# FLUSH PRIVILEGES;

# Change 
# REVOKE ALL PRIVILEGES ON *.* FROM 'freshnewsletter'@'localhost'; 
# REVOKE GRANT OPTION ON *.* FROM 'freshnewsletter'@'localhost'; 
# GRANT SELECT, INSERT, UPDATE, DELETE, FILE ON *.* TO 'freshnewsletter'@'localhost' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
