	function emoticons(msg){
		var emoticons = {
		    ':-)' : 'smile.gif',
		    ':)'  : 'smile.gif',
		    ':]'  : 'smile.gif',
		    ':}'  : 'smile.gif',
		    ':D'  : 'haha.gif',
		    ':d'  : 'ha.gif',
		    ':P'  : 'pbig.gif',
		    ':p'  : 'p.gif',
		    ':hug'  : 'hug.gif',
		    ':crazy'  : 'crazy.gif',
		    ':spacer'  : 'spacer.gif',
		    ':bigdog'  : 'dog.gif',
		    ':cutedog'  : 'cutedog.gif',
		    ':angrydog'  : 'angrydog.gif',
		    ':hoho'  : 'hoho.gif',
		    ':bighi'  : 'big.gif',
		    ':haha'  : '1hoho.gif',
		    ':lick' : 'lick.gif',
		    ':santa' : 'santa.gif',
		    ':target' : 'target.gif',
		    ':stupid' : 'stupid.gif',
		    ':finger' : 'finger.gif',
		    ':sprint' : 'sprint.gif',
		    ':hura'  : 'hura.gif',
		    ':hehe'  : 'hehe.gif',
		    ':boo'  : 'boo.gif',
		    ':rain'  : 'rain.gif',
		    ':happy'  : 'happy.gif',
		    ':1happy'  : 'happy1.gif',
		    ':love'  : 'love.gif',
		    ':1love'  : 'love1.gif',
		    ':roll'  : 'roll.gif',
		    ':1roll' : 'roll1.gif',
		    ':1dance'  : 'dance.gif',
		    ':scared'  : 'scared.gif',
		    ':angry' : 'angry.gif',
		    ':1angry' : 'angry1.gif',
		    ':faint' : 'faint.gif',
		    ':jezor' : 'jezor.gif',
		    ':music' : 'music.gif',
		    ':brum' : 'drum.gif',
		    ':grzyb' : 'grzyb.gif',
		    ':fuck' : 'fuck.gif',
		    ':hop' : 'hop.gif',
		    'XD' : 'woohoo.gif',
		    'xd' : 'woohoo.gif',		    
		    ':ave' : 'ave.gif',
		    ':poke' : 'poke.gif',
		    ':kiss' : 'kiss.gif',
		    ':jupi' : 'jupi.gif',
		    ':hi' : 'hi.gif',
		    ':angel' : 'angel.gif',
		    ':tany' : 'tany.gif',
		    ':flowers' : 'flowers.gif',
		    ':gift' : 'gift.gif',
		    ':hello' : 'hello.gif',
		    ':1hello' : '1hello.gif',
		    ':tomato' : 'pomidor.gif',
		    ':ciao' : 'ciao.gif',
		    ':nono' : 'nono.gif',
		    ':noway' : 'noway.gif',
		    ':sayno' : 'sayno.gif',
		    ':sorry' : 'sorry.gif',
		    ':byebye' : 'byby.gif',
		    ':saybye' : 'saybye.gif',
		    ':pissing' : 'pissing.gif',
		    ':ecstasy' : 'ecstasy.gif',
		    ':you' : 'you.gif',
		    ':bomb' : 'bomb.gif',
		    ':lol' : 'panda.gif',
		    ':evil' : 'evil.gif',
		    ':green' : 'green.gif',
		    ':alien' : 'alien.gif',
		    ':flagpl' : 'flagpl.gif',
		    ':goal' : 'goal.gif',
		    ':football' : 'football.gif',
		    ':win' : 'win.gif',
		    ':boxing' : 'boxing.gif',
		    ':1boxing' : '1boxing.gif',
		    ':clown' : 'clown.gif',
		    ':cool' : 'cool.gif',
		    ':beer' : 'beer.gif',
		    ':hot' : 'hot.gif',
		    ':kawa' : 'hot.gif',
		    ':cheers' : 'cheers.gif',
		    ':macho' : 'macho.gif'
		  }
		for ( smile in emoticons )
		{
			var surl = "http://"+window.location.host+"/woo/wp-content/plugins/bziqchat/emoticons/";
		   // msg = msg.replace(smile, '<img src="' + surl + emoticons[smile] + '" />');
		   msg = msg.split(smile).join('<img class="emo" src="' + surl + emoticons[smile] + '" />');
		}		
		return msg;
	}
