<?php
    $a = $arrayName = array(
    'u' => 'smile.gif',
    'f'  => 'smile.gif',
    'z'  => 'smile.gif',
    'b'  => 'smile.gif',
    'D'  => 'haha.gif',
    'd'  => 'ha.gif',
    'P'  => 'pbig.gif',
    'p'  => 'p.gif',
    'X' => 'milcz.gif',
    'x' => 'milcz.gif',
    'O' => 'bigsurprise.gif',
    'o' => 'bigsurprise.gif',		    
    'hug'  => 'hug.gif',
    'crazy'  => 'crazy.gif',
    'spacer'  => 'spacer.gif',
    'bigdog'  => 'dog.gif',
    'cutedog'  => 'cutedog.gif',
    'angrydog'  => 'angrydog.gif',
    'hoho'  => 'hoho.gif',
    'bighi'  => 'big.gif',
    'haha'  => '1hoho.gif',
    'lick' => 'lick.gif',
    'santa' => 'santa.gif',
    'target' => 'target.gif',
    'stupid' => 'stupid.gif',
    'finger' => 'finger.gif',
    'sprint' => 'sprint.gif',
    'hura'  => 'hura.gif',
    'hehe'  => 'hehe.gif',
    'boo'  => 'boo.gif',
    'rain'  => 'rain.gif',
    'happy'  => 'happy.gif',
    '1happy'  => 'happy1.gif',
    'love'  => 'love.gif',
    '1love'  => 'love1.gif',
    'roll'  => 'roll.gif',
    '1roll' => 'roll1.gif',
    '1dance'  => 'dance.gif',
    'scared'  => 'scared.gif',
    'angry' => 'angry.gif',
    '1angry' => 'angry1.gif',
    'faint' => 'faint.gif',
    'jezor' => 'jezor.gif',
    'music' => 'music.gif',
    'brum' => 'drum.gif',
    'grzyb' => 'grzyb.gif',
    'fuck' => 'fuck.gif',
    'hop' => 'hop.gif',
    'woo' => 'woohoo.gif',		    
    'ave' => 'ave.gif',
    '1poke' => '1poke.gif',
    'kiss' => 'kiss.gif',
    'jupi' => 'jupi.gif',
    'hi' => 'hi.gif',
    'angel' => 'angel.gif',
    'tany' => 'tany.gif',
    'flowers' => 'flowers.gif',
    'gift' => 'gift.gif',
    'hello' => 'hello.gif',
    '1hello' => '1hello.gif',
    'tomato' => 'pomidor.gif',
    'ciao' => 'ciao.gif',
    '9nono' => 'nono.gif',
    'nono' => 'nono.gif',
    'noway' => 'noway.gif',
    'sayno' => 'sayno.gif',
    'sorry' => 'sorry.gif',
    'byebye' => 'byby.gif',
    'saybye' => 'saybye.gif',
    'pissing' => 'pissing.gif',
    'ecstasy' => 'ecstasy.gif',
    'you' => 'you.gif',
    'bomb' => 'bomb.gif',
    'lol' => 'panda.gif',
    'evil' => 'evil.gif',
    'green' => 'green.gif',
    'alien' => 'alien.gif',
    'flagpl' => 'flagpl.gif',
    'goal' => 'goal.gif',
    'football' => 'football.gif',
    'win' => 'win.gif',
    'boxing' => 'boxing.gif',
    '1boxing' => '1boxing.gif',
    'clown' => 'clown.gif',
    'cool' => 'cool.gif',
    'beer' => 'beer.gif',
    'hot' => 'hot.gif',
    'kawa' => 'hot.gif',
    'cheers' => 'cheers.gif',
    'macho' => 'macho.gif',
    'cat' => 'cat.gif',
    'cold' => 'cold.gif',
    'coffe' => 'coffe.gif',
    'butla' => 'butla.png',
    'heniek' => 'heniek.png',
    'shocked' => 'shocked.gif',
    'sayoh' => 'sayoh.gif',
    'cwiety' => 'cwiety.gif',
    'mask' => 'mask.gif',
    'shoq' => 'bigsurprise.gif',		    
    'soda' => 'soda.png');

$s .= '.xx{background: ';
foreach ($a as $v) {
	$s .= 'url(https://qflash-fxstar.rhcloud.com/emoticons/'.$v.'),';
	$x .= '<img src="https://qflash-fxstar.rhcloud.com/emoticons/'.$v.'">';
}
$s .= '}';
file_put_contents('emoticons.css', $s);
?>
<div class="xx" style="display: none; width: 1px; height: 1px;">
	<?php echo $x; ?>
</div>
