# Generated by iptables-save v1.4.14 on Sat Aug  8 11:22:11 2010
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]

### localhost traffic
-A INPUT -i lo -j ACCEPT
### log all incoming traffic
-A INPUT -j LOG --log-prefix "INP-ALL "

### SSH server port
-A INPUT -p tcp --dport 22 -j ACCEPT

### WWW(HTTP),HTTPS ports
-A INPUT -p tcp --dport 80 -j ACCEPT
-A INPUT -p tcp --dport 443 -j ACCEPT

### Mysql server port
-A INPUT -p tcp --dport 3306 -j ACCEPT

### SMTP,IMAP,POP
-A INPUT -p tcp --dport 25 -j ACCEPT
-A INPUT -p tcp --dport 110 -j ACCEPT
-A INPUT -p tcp --dport 143 -j ACCEPT
-A INPUT -p tcp --dport 465 -j ACCEPT
-A INPUT -p tcp --dport 587 -j ACCEPT
-A INPUT -p tcp --dport 995 -j ACCEPT

### Or in one rule
# -A INPUT -p tcp -i eth0 -m multiport --dports 465,110,995,587,143,21,22,25,80,443 -j ACCEPT

-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7
-A INPUT -j DROP
-A FORWARD -j DROP
-A OUTPUT -j LOG --log-prefix "OUT-ALL "
COMMIT
# Completed on Sat Aug  8 11:22:11 2010


## show iptables list
## iptables -L
## iptables -t nat -L -v -n

## open port
## -A INPUT -p tcp -i eth0 --dport 22 -j ACCEPT

## allow lo
## iptables -I INPUT 1 -i lo -j ACCEPT
## 
## log to syslog from bash
## iptables -I INPUT 5 -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7
## from iptables file
## -A INPUT -m limit --limit 5/min -j LOG --log-prefix "iptables denied: " --log-level 7

## more logging
## -A INPUT -j LOGNDROP
## -A LOGNDROP -p tcp -m limit --limit 5/min -j LOG --log-prefix "Denied TCP: " --log-level 7
## -A LOGNDROP -p udp -m limit --limit 5/min -j LOG --log-prefix "Denied UDP: " --log-level 7
## -A LOGNDROP -p icmp -m limit --limit 5/min -j LOG --log-prefix "Denied ICMP: " --log-level 7
## -A LOGNDROP -j DROP
